# Generated by Django 2.1.5 on 2019-09-12 06:43

from django.db import migrations, models


def copy_approved_status_value_to_new_field(apps, schema_editor):
    LeaveRequest = apps.get_model('calendar_manager', 'LeaveRequest')
    for request in LeaveRequest.objects.all():
        request.status = int(request.is_approved)
        request.save()


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'Pending')], default=2, verbose_name='Request Status'),
        ),
        migrations.RunPython(copy_approved_status_value_to_new_field)
    ]
