# Generated by Django 2.1.5 on 2019-09-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0002_leaverequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='is_approved',
        ),
    ]
