# Generated by Django 2.1.5 on 2019-12-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0003_remove_leaverequest_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rejected'), (1, 'Approved'), (2, 'Pending')], default=2, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='type',
            field=models.IntegerField(choices=[(0, 'Personal'), (1, 'Sick')], default=0, verbose_name='Leave type'),
        ),
    ]
