# Generated by Django 2.1.5 on 2019-12-27 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0004_alter_verbose_name_of_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('all_day', models.BooleanField(default=False)),
                ('start', models.TimeField(default=datetime.time(10, 0), verbose_name='Start time')),
                ('end', models.TimeField(default=datetime.time(18, 0), verbose_name='End time')),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
