# Generated by Django 2.1.5 on 2020-02-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_manager', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='Remote work'),
        ),
    ]
